### ISSUE TITLE
Return no record after request contract detail

### ISSUE THREAD

**Issue by ben1628** [dshe/InterReact#1]
var contract = new Contract
            {
                SecurityType = InterReact.StringEnums.SecurityType.Stock,
                Symbol = "MSFT",
                Currency = "USD",
                Exchange = "SMART"
            };

            //client.Request.RequestCurrentTime();

            //var test = await client.Services.HistoricalDataObservable(contract);

            var contractDetailsList = await client.Services.ContractDetailsObservable(contract);

            var contractDetails = contractDetailsList.Single();

Var contractDetails returns zero.

When I debug the solution,  IB gateway log shows the contract detail is returned, yet the program doesn't seem to hit the contractDetail.

Any idea?

Thanks.

**Comment by dshe** [comment]
Thank you for your inquiry.

Please see the ContractDetailsServiceTests class in the InterReact.Tests project to see how to retrieve ContractDetails.
