### ISSUE TITLE
Modifying orders results in "Duplicate order id"

### ISSUE THREAD

**Issue by prodoramatlin** [dshe/InterReact#12]
When submitting an updated order using PlaceOrder the order is not updated and the IB Gateway returns "Duplicate order id"

Referring to this section from IB's docs about modifying orders:
[Modifying Orders](https://interactivebrokers.github.io/tws-api/modifying_orders.html)

**Comment by prodoramatlin** [comment]
Solved by adding a short delay between creation and editing.

**Comment by dshe** [comment]
Thank you for reporting this issue.

**Comment by dshe** [comment]
Please see: `SystemTests: Orders.Monitor.OrderMonitorCancellationTest()`
