### ISSUE TITLE
The data format from IB doesn't correspond with HistoricalDataBar no more

### ISSUE THREAD

**Issue by prodoramatlin** [dshe/InterReact#13]
Hi!

It looks like IB has updated the format for HistoricalDataBar. What can see there no longer is a gap that was handled like:

r.ReadString(); /* string hasGaps */

This makes the line after crash:

Count = r.ReadInt();

Is it possible to find the IB specs for the different messages?

**Comment by dshe** [comment]
Yes, you are correct. I have updated the `HistoricalData` code. 

Please see: `SystemTests: History.HistoryTests`

Thank you for reporting this issue.

**Comment by prodoramatlin** [comment]
Working fine now! Thanks!
