### ISSUE TITLE
HistoricalBarSize, OneSecond is incorrectly assigned.

### ISSUE THREAD

**Issue by pauliusdotpro** [dshe/InterReact#16]
In HistoricalBarSize class, OneSecond is set as "1 sec". However as stated in IBKR error message: 
"Historical data bar size setting is invalid. Legal ones are: 1 secs, 5 secs, 10 secs, 15 secs, 30 secs, 1 min, 2 mins, 3 mins, 5 mins, 10 mins, 15 mins, 20 mins, 30 mins, 1 hour, 2 hours, 3 hours, 4 hours, 8 hours, 1 day, 1W, 1M--"
It is supposed to be set to "1 secs"

**Comment by dshe** [comment]
In the HistoricalBarSize class, OneSecond is now "1 secs". Thank you!
