### ISSUE TITLE
Errors during the use

### ISSUE THREAD

**Issue by memoryfraction** [dshe/InterReact#18]
Met several errors while using the latest master branch

1 Compiler errors as below
![1](https://github.com/dshe/InterReact/assets/18358791/c25a8c4d-605c-4453-888e-ad145ba92979)
commented the compiler errors and continue.

2 unit test failures
![image](https://github.com/dshe/InterReact/assets/18358791/7fefd833-551e-4e99-b79e-73b9bc4c8a3a)

IBKR Pro Account + IBGW 10.19 Version + Windows 10 Pro 22H2
![image](https://github.com/dshe/InterReact/assets/18358791/c1b51f8c-8d56-45fe-8ecb-d5c0ffc1c9db)

Wonder, is it only me met these errors or errors happens widely?  the repo appears to be good I test during Nov 2023. 
I don't know what happened or anything wrong I did?
Any suggestion?

Thanks

**Comment by dshe** [comment]
The complier errors are for some certain tests. You can disable/skip those tests.

The failed unit tests will possibly succeed if you login with a different account. Try the demo account.

**Comment by memoryfraction** [comment]
Thanks for the response.
I tried the paper account and the trade account, and got the same failed test result.
What do you mean by "the demo account"?

**Comment by dshe** [comment]
In TWS, you can log in to the demo account by clicking the "Try The Demo" link located below the blue "Log in" button.

**Comment by memoryfraction** [comment]
thx for the response.
Tried the "Try The Demo", it did works for the summary tests(3)
But, when I switch to the IB Gateway with the trade account(production environment), SystemTests->Account ->Summary all fail
And, found that: the messages is 0 during the debug, thinking why? 
So, based on the found phenomenon, what should I do if I need to use IBGW and InterReact to get the Account Summary Info.

![image](https://github.com/dshe/InterReact/assets/18358791/e16cd598-f1e1-4892-8100-9e4791ce37a9)

![image](https://github.com/dshe/InterReact/assets/18358791/0514740a-a91c-4b7e-b023-00e0e5ed9677)

**Comment by dshe** [comment]
In line 20, try changing "FromMilliseconds" to "FromSeconds".

**Comment by memoryfraction** [comment]
Cool, it works now.  Can I know why it works by changing the parameter of FromMilliseconds() from 100 to 1000?

**Comment by dshe** [comment]
100ms was not enough time to receive a response to RequestAccountSummary() from TWS.
