### ISSUE TITLE
A question about the as-is design

### ISSUE THREAD

**Issue by memoryfraction** [dshe/InterReact#22]
In the below code, it uses Take(timeSpan) to wait the response, which may cause concurrent issue.
Why not use the event , e.g. PlaceOrderCompleteEvent, to let the caller know: "Hi,  subscribe this event, when I am ready, I let you know"
e.g. this article: https://zhuanlan.zhihu.com/p/30341365
 ```
public async Task<IList<OpenOrder>> RequestOpenOrdersAsync()
 {
     Task<IList<OpenOrder>> task =
         Response
         .OfType<OpenOrder>()
         **.Take(TimeSpan.FromMilliseconds(500))**
         .ToList()
         .ToTask();
     Request.RequestOpenOrders();
     var orders = await task;
     return orders;
 }
```
Feel free to correct me if my understanding is incorrect.

**Comment by dshe** [comment]
InterReact uses reactive programming (Reactive extensions) rather than events.

The reason for the potential conflict with orders is due to a flaw with part of the TWS API design (the request does not include an id).
