### ISSUE TITLE
Alert when placing order

### ISSUE THREAD

**Issue by zenchanhk** [dshe/InterReact#3]
Hi,

When I'm trying to place a simple order with OrderType of Market Order and Limit Order, they both returned with alert message: "Order processing failed. Algorithm definition not found. Code=439. Id=1180."
`var order = new Order 
            {
                TradeAction = TradeAction.Buy,
                TotalQuantity = 100,
                OrderType = OrderType.Market
            };`
Highly appreciate for any clues.

**Comment by zenchanhk** [comment]
I've run the test in the project, PlaceOrder test didn't pass. Attached please find the test result.
![test](https://user-images.githubusercontent.com/10985245/68132866-5d5c9980-ff5a-11e9-978c-df08063a9ff0.png)

**Comment by zenchanhk** [comment]
I've noticed that `Config.ServerVersionCurrent = 100` after connection initiated, but `Config.ServerVersionMin` is `102`, is it normal?

**Comment by dshe** [comment]
Thank you for your inquiry.

The latest version of InterReact has improved order processing. Please see the demo program "HelloWorld".
