### ISSUE TITLE
Placing order error 

### ISSUE THREAD

**Issue by Sarmkadan** [dshe/InterReact#4]
when creating new order and trying to place it 
 Order neworder = new Order();
            neworder.OrderType = OrderType.Limit;
            neworder.TradeAction = TradeAction.Buy;
            neworder.LimitPrice = 1;
            neworder.TimeInForce = TimeInForce.Day;
            neworder.TotalQuantity = 1;
            
            neworder.AlgoStrategy  = "Adaptive";
            neworder.AlgoParams.Add(new Tag("adaptivePriority", "Patient"));  <-- here 

get error 

Alert: {RequestId:1823, OrderId:1823, Code:320, Message:"Error reading request.Message id 1823.  Unable to parse data. java.lang.NumberFormatException: For input string: "Patient"", AlertType:HasId}

**Comment by dshe** [comment]
Thank you for your inquiry.

The latest version of InterReact has improved order processing. Please see the demo program "HelloWorld".
