### ISSUE TITLE
OrderStatusReports don't appear to be handled

### ISSUE THREAD

**Issue by cs-simtrader** [dshe/InterReact#8]
I updated to the latest and tried using the OpenOrdersObservable and it doesn't appear to be handling/receiving the OrderStatusReports. A new order will cause a "Submitted" OrderStatusReport to be received. When it's cancelled a "Cancelled" report should be received.

**Comment by cs-simtrader** [comment]
[Fact]
public async Task TestOrderStatus()
{
    if (!Client.RemoteIPEndPoint.Port.IsIBDemoPort())
        throw new Exception("Cannot place order. Not the demo account");

    var requestId = Client.Request.GetNextRequestId();
    var orderId = Client.Request.GetNextOrderId();

    long statusReceived = 0;
    IObservable<object> orderStatusService = Client.Service.CreateOpenOrdersObservable();
    var orderStatusObserver = orderStatusService.Subscribe(async x =>
    {
        if (!(x is InterReact.OrderStatusReport))
            return;

        OrderStatusReport? status = x as InterReact.OrderStatusReport;

        if (status != null)
        {
            Interlocked.Increment(ref statusReceived);
            Logger.LogInformation("Status Received: ", status.Status);
        }
    });


    var taskOpenOrder = Client.Response
        .OfType<OpenOrder>()
        .Where(x => x.OrderId == orderId)
        .FirstAsync()
        .Timeout(TimeSpan.FromSeconds(5))
        .ToTask();


    var order = new Order
    {
        OrderId = orderId,
        OrderAction = OrderAction.Buy,
        TotalQuantity = 100,
        OrderType = OrderType.Limit,
        LimitPrice = 1 // below market
    };

    Client.Request.PlaceOrder(orderId, order, StockContract1);

    await taskOpenOrder;
    Client.Request.RequestAllOpenOrders();
    
    
   // cancel the order
    var taskCancelled = Client.Response
        .OfType<OrderStatusReport>()
        .Where(x => x.OrderId == orderId)
        .Where(x => x.Status == OrderStatus.Cancelled)
        .FirstAsync()
        .Timeout(TimeSpan.FromSeconds(5))
        .ToTask();

    Client.Request.CancelOrder(orderId);

    await taskCancelled;
   
    Client.Request.RequestAllOpenOrders();
    Thread.Sleep(4000);

    long lastValue = Interlocked.Read(ref statusReceived);
    if (lastValue == 0) 
    {
        throw new Exception("No order status received");
    }
    else
    {
        Logger.LogInformation("Number Status Reports Received: ", lastValue);
    }
}

**Comment by dshe** [comment]
I have updated InterReact. There are many changes. Please see:

**SystemTests / Orders / Monitor / OrderMonitorCancellationTest**.

Thank you for your support.
